# NOTEBOOK SETTINGS
[notebook]
dir = "~/notes"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}-{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 8

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Patrick"

# GROUP OVERRIDES
[group.daily]
paths = ["journal"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.area]
paths = ["areas"]

[group.area.note]
template = "area.md"

[group.project]
paths = ["projects"]

[group.project.note]
template = "project.md"

[group.atomicnote]
template = "atomic-note.md"

[group.blogpost]
template = "blog-post.md"

[group.hub.note]
template = "hub.md"

[group.literaturenote]
template = "literature-note"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = false
# Enable support for wiki-style [[links]]
wiki-links = false


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/zsh"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

# Edit the last modified note.
last = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Edit areas
areas = "zk edit -t area -i"

# Edit projects
projects = "zk edit -t project -i"

# Edit hubs
hubs = "zk edit -t hub -i"

# new note
n = 'zk new --no-input "$ZK_NOTEBOOK_DIR" --title $argv'

# new journal entry
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'

# new area entry
na = 'zk new --no-input "$ZK_NOTEBOOK_DIR/areas" --title $argv'

# new project entry
np = 'zk new --no-input "$ZK_NOTEBOOK_DIR/projects" --title $argv'

# new hub
nh = 'zk new --no-input "$ZK_NOTEBOOK_DIR" --group hub --title $argv'

# new atomic note
nan = 'zk new --no-input "$ZK_NOTEBOOK_DIR" --group atomicnote --title $argv'

# new blog post
nbp = 'zk new --no-input "$ZK_NOTEBOOK_DIR" --group blogpost --title $argv'

# new literature note
nln = 'zk new --no-input "$ZK_NOTEBOOK_DIR" --group literaturenote --title $argv'

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
# Warn when notes link here without backlinks.
missing-backlink = { level = "warning", position = "bottom" }
